### ISSUE TITLE
Subdomain still access main domain

### ISSUE THREAD

**Issue by mlazuardy-dyned** [madhusudanbabar/k-domains#2]
your blog subdomain still can access the root domain 

example
https://blog.madhusudan.live/work

**Comment by madhusudanbabar** [comment]
Yeah, thanks for pointing that, we can disable those routes in Auth guards, I'll implement that in future releases

**Comment by madhusudanbabar** [comment]
@mlazuardy-dyned actually there's misunderstanding,
Those pages are intentionally shared across all subdomains, 
There's no cross domain site access, I'm removing those routes.
