### ISSUE TITLE
Doesn't seem to work for me

### ISSUE THREAD

**Issue by miketeix** [madhusudanbabar/k-domains#5]
Hi there,

here's my nuxt.config buildModules section:
```
 buildModules: [
    [
      'k-domains',
      {
        subDomains: ['app'],
        rootDomain: 'root',
      },
    ],
    [
      '@nuxtjs/router',
      {
        keepDefaultRouter: true, // this line is mandatory...
      },
    ],
  ],

```

and so I expect  `app.myDomain/` to render the index.vue inside my `pages/app` directory

similarly, I expect `myDomain/` to render the index.vue inside my `pages/root` directory

Instead I get a `This page could not be found` nuxt error:
![image](https://user-images.githubusercontent.com/3904862/95415411-2deaa580-08fe-11eb-9cc1-7a24612d6c64.png)

Am I missing something?

thanks!

**Comment by madhusudanbabar** [comment]
Can you share your pages tree? 
I guess you may have an index.vue page in your `pages` directory.
Can you paste the error message? I'm unable to see the white-colored text.

**Comment by miketeix** [comment]
Hey thanks for the reply, here's my page tree:

```
pages
   /app
       index.vue
       /otherPage
       /otherPage
   /root
      index.vue
      /otherPage
```

Oh the white-colored text is actually the footer of the page, so the error is "Page is not found".

Should I not have an index.vue in my pages directory?

**Comment by shoxadomokai** [comment]
@miketeix did you ever get a solution to this? I'm having the same problem.

I also get the following warnings when building nuxt begins building. I don't know if related or not;

- No router.js found in [project_directory]

- no proxy defined on top-level

**Comment by madhusudanbabar** [comment]
> @miketeix did you ever get a solution to this? I'm having the same problem.
> 
> I also get the following warnings when building nuxt begins building. I don't know if related or not;
> 
> * No router.js found in [project_directory]
> * no proxy defined on top-level

you need to add the k-domains first in the `nuxt.config.js` or at least before the `@nuxtjs/router` module,
the warning `no router.js found` is coming from the `@nuxtjs/router`.
