### ISSUE TITLE
Can't resolve 'child_process' 'fs' 'module'

### ISSUE THREAD

**Issue by tuananhbfs** [madhusudanbabar/k-domains#9]
I tried using k-modules for my project, followed the full instructions and had the following problem. I hope everyone will help me

**Comment by madhusudanbabar** [comment]
Can you post the error logs?

**Comment by tuananhbfs** [comment]
I tried to find the cause of the error by deleting the plugins in nuxt.config.js
And here is the reason. I'm not sure why it conflicts.


`const webpack = require('webpack');	

export default {

build: {
		plugins: [
		new webpack.ProvidePlugin({
			$: 'jquery',
			jQuery: 'jquery',
			'window.jQuery': 'jquery'
		})
		],
	},
}`

**Comment by madhusudanbabar** [comment]
actually, it has nothing to do with plugins but without the logs can't proceed further
